# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testAPISCB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testAPISCB

  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'AlamofireImage', '~> 4.0.0-beta.3'
  pod 'YoutubePlayer-in-WKWebView', '~> 0.3.0'
  pod 'FMDB', '~> 2.7.5'
  pod 'QRCodeReader.swift', '~> 10.1.0'
  pod 'QRCode', '~> 2.0'
  pod 'Charts', '~> 3.3.0'

end
