server:
  port: 8090
  servlet:
    context-path: /api
spring:
  application:
    name: ezbudgetservice

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/plan_db
    username: Hanchai
    password: Big!89619

  UserService:
    host: http://localhost:8081/api/user
    endpoint:
      getUser: get-user

restTemplate:
  connectionTimeOut: 5000
  readTimeOut: 10000
